# Generated by Django 5.0.7 on 2024-07-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image'),
        ),
    ]
