# Generated by Django 5.0.7 on 2024-07-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
