# Generated by Django 5.0.7 on 2024-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
